codes/RetailProject/RetailProject/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from RetailProject import settings
from django.conf.urls.static import static
from order_api.urls import api_router, api_urlpatterns
from django.views.generic import TemplateView
from RetailProject import settings

local_sync_paths = [path('ap-sync/', include('ap_sync_data.urls'))]
cloud_sync_paths = [path('cloud-manager/', include('retail_cloud_manager.urls'))]

urlpatterns = [
    path('', include('order_manager.urls')),
    path('admin/', admin.site.urls),
    path('order-api/', include(api_router.urls )),
    path('order-api/', include(api_urlpatterns)),
    path('order-app/', include('order_app.urls')),
    path('order-manager/', include('order_manager.urls')),
    # path('cloud-manager/', include('retail_cloud_manager.urls')),
    # path('ap-sync/', include('ap_sync_data.urls')),
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': os.path.join(settings.BASE_DIR, 'static')}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
if settings.DJANGO_SERVER_TYPE == 'local':
  urlpatterns += local_sync_paths
else:
  urlpatterns += cloud_sync_paths
  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'order_manager.views.error_404'

codes/RetailProject/order_api/urls.py
from rest_framework import routers
from order_api.controller.product_ctr import ProductViewSet, update_inventory
from order_api.controller.category_ctr import ProductCategoryViewSet
from order_api.controller.discount_package_ctr import DiscountPackageViewSet
from order_api.controller.table_ctr import TableViewSet
from order_api.controller.order_place_ctr import OrderPlaceViewSet, cancel_order
from order_api.controller.authentication_ctr import  custom_login, custom_register, custom_add_device_id
from order_api.controller.payment_ctr import  create_order, payment_ipn
from django.urls import path

app_name = 'order-app'
api_router = routers.DefaultRouter()
api_router.register(r'products', ProductViewSet)
api_router.register(r'categories', ProductCategoryViewSet)
api_router.register(r'discount-packages', DiscountPackageViewSet)
api_router.register(r'tables', TableViewSet)
api_router.register(r'orders', OrderPlaceViewSet)

api_urlpatterns = [
    path('auth/custom-login/', custom_login, name='custom_login'),
    path('auth/custom-register/', custom_register, name='custom_register'),
    path('create-order/', create_order, name='create_order'),
    path('update-eventory/', update_inventory, name='update_inventory'),
    path('add-device/', custom_add_device_id, name='custom_add_device_id'),
    path('payment-ipn/', payment_ipn, name='payment_ipn'),
    path('cancel-order/', cancel_order, name='cancel_order'),
]

codes/RetailProject/order_manager/urls.py
from django.urls import path
from order_manager import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Index
    path('', views.dashboard, name="index"),

    # Pages
    path('dashboard/', views.dashboard, name="dashboard"),
    # path('transaction/', views.transaction, name="transaction"),
    path('customers/', views.customerManager, name="customers"),
    path('products/', views.productManager, name="products"),
    path('product/add', views.addProduct, name="product_add"),
    path('product/edit', views.editProduct, name="product_edit"),
    path('categories/', views.categoryManager, name="categories"),
    path('category/add', views.addCategory, name="category_add"),
    path('category/edit', views.editCategory, name="category_edit"),
    path('orders/', views.orderManager, name="orders"),
    path('order-detail/', views.orderDetailManager, name="order_detail"),
    path('order/add', views.addOrder, name="order_add"),
    path('discount-packages/', views.discountPackageManager, name="discount_packages"),
    path('discount-package/add', views.addDiscountPackage, name="discount_package_add"),
    path('discount-package/edit', views.editDiscountPackage, name="discount_package_edit"),
    path('settings/', views.settings, name="settings"),
    path('statistic/', views.statistic, name="statistic"),
    path('login/', views.UserLoginView.as_view(), name="login"),
    path('tables/', views.tableManager, name="tables"),
    path('tables/add', views.addTable, name="table_add"),
    path('tables/edit', views.editTable, name="table_edit"),
    path('warehouse/', views.warehouseManager, name="warehouse"),

    # Authentication
    # path('accounts/register/', views.register_view, name="register"),
    path('accounts/login/', views.UserLoginView.as_view(), name="login"),
    path('accounts/logout/', views.logout_view, name="logout"),
#     path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
#     path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
#         template_name='accounts/password-change-done.html'
#     ), name="password_change_done"),
#     path('accounts/password-reset/', views.UserPasswordReseStView.as_view(), name="password_reset"),
#     path('accounts/password-reset-confirm/<uidb64>/<token>/',
#         views.UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"
#     ),
#     path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
#         template_name='accounts/password-reset-done.html'
#     ), name='password_reset_done'),
#     path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
#         template_name='accounts/password-reset-complete.html'
#   ), name='password_reset_complete'),

    path('accounts/lock/', views.lock, name="lock"),

    # Errors
    path('error/403/', views.error_403, name="error_403"),
    path('error/404/', views.error_404, name="error_404"),
    path('error/500/', views.error_500, name="error_500"),
]

codes/RetailProject/order_api/models.py
# Create your models here.
from django.db import models
from PIL import Image
from datetime import datetime
from ap_sync_data.models import SyncUpdateModel
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from RetailProject import settings


# Create your models here.
class Store(SyncUpdateModel):
    name = models.CharField(max_length=512, null=True, blank=True)
    slug = models.SlugField(max_length=10, unique=True ,db_index=True)
    is_active = models.BooleanField(default=True)
    description =  models.CharField(max_length=512, null=True, blank=True)
    location =  models.CharField(max_length=512, null=True, blank=True)
    created_date   = models.DateTimeField(auto_created=True)
    def thumbnail_directory_path(Client, filename):
        dirname = datetime.now().strftime('%y/%m/%d')
        return 'uploads/order-app/{0}/store/{1}'.format(dirname, filename)

    thumbnail = models.FileField(upload_to=thumbnail_directory_path, verbose_name="Hình ảnh",
                              default='', null=True)
    def __str__(self):
        return f'{self.name}'
    
    def save(self, force_insert=False, force_update=False):
        size = 300, 300
        super(Store, self).save(force_insert, force_update)
        if self.id is not None:
            if self.thumbnail:
                try:
                    image = Image.open(self.thumbnail.name)
                    # image = image.resize((100, 100), Image.ANTIALIAS)
                    image.thumbnail(size, Image.ANTIALIAS)
                    image.save(self.thumbnail.name)
                except IOError:
                    print("Co loi trong qua trinh resize")
class AccessPoint(models.Model):
    UNCONNECTED = 'unconnected'
    UPDATING = 'updating'
    CONNECTED = 'connected'
    DISCONNECTED = 'disconnected'
    UPDATE_FAILED = 'update_failed'
    SYNC_COMPLETED = 'sync_completed'

    STATUS_LABELS = (
        (UNCONNECTED, 'Chưa kết nối'),
        (UPDATING, 'Đang cập nhật'),
        (CONNECTED, 'Đã kết nối'),
        (DISCONNECTED, 'Mất kết nối'),
        (UPDATE_FAILED, 'Cập nhật lỗi'),
        (SYNC_COMPLETED, 'Đồng bộ hóa thành công'),
    )

    STATUS_COLORS = {
        UNCONNECTED: '#795548',
        UPDATING: 'lightblue',
        CONNECTED: 'lightgreen',
        DISCONNECTED: 'orange',
        UPDATE_FAILED: 'red',
        SYNC_COMPLETED: 'green',
    }

    name = models.CharField(max_length=512, null=True, blank=True)
    # store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank=True)
    ip_address = models.CharField(max_length=64, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=32,default=UNCONNECTED, choices=STATUS_LABELS)
    status_description = models.TextField(null=True, blank=True)
    last_online = models.DateTimeField(null=True, blank=True)
    data_version = models.CharField(max_length=64, null=True, blank=True, default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} | {self.ip_address}'

    def get_status_color(self):
        return self.STATUS_COLORS[self.status]

class AccessPoint2Store(models.Model):
    access_point = models.ForeignKey(AccessPoint,  on_delete=models.CASCADE, related_name='access_points')
    store = models.ForeignKey(Store, on_delete=models.CASCADE)

class TrackingChangeModel(models.Model):
    def save(self, *args, **kwargs):
        if settings.DJANGO_SERVER_TYPE == 'cloud':
            try: 
                access_2_stores = AccessPoint2Store.objects.filter(store_id=self.store_operate_id)
                for ap2store in access_2_stores:
                    ap = AccessPoint.objects.get(pk=ap2store.access_point.id)
                    ap.data_version = int(ap.data_version) + 1
                    ap.save()
            except:
                pass
        super(TrackingChangeModel, self).save(*args, **kwargs)

    class Meta:
        abstract = True

class MyUserManager(BaseUserManager):
    def create_user(self, username,phone_number=None, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError("Users must have an username")

        user = self.model(
            username=username,
            phone_number=phone_number
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, username, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username=username,
        )
        user.is_active=True
        user.is_admin=True
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, password=None):
        """
        creates a superuser with email and password
        """
        user = self.create_user(
            username=username,
        )
        user.is_active=True
        user.is_admin=True
        user.set_password(password)
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser,SyncUpdateModel):
    STORE_MANAGER = 'store_manager'
    CUSTOMER = 'customer'
    EMPLOYEE = 'employee'
    
    ROLES_CHOICES = [
        (STORE_MANAGER, 'Quản lý'),
        (CUSTOMER, 'Khách hàng'),
        (EMPLOYEE, 'Nhân viên'),
    ]
    class Meta:
        verbose_name_plural = 'Custom User'

    username = models.CharField(max_length=20, unique=True,null=False, blank=False )
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=CUSTOMER)
    store_operate = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank=True)
    device_id = models.CharField(max_length=512, null=True, blank=True)
    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    # REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        # "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        # "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        """Is the user a staff member"""
        return self.is_admin
    
    def save(self, *args, **kwargs):
        # Validate and normalize the phone number before saving
        # parsed_number = phonenumbers.parse(self.phone_number, None)
        # if not phonenumbers.is_valid_number(parsed_number):
        #     raise ValueError("Invalid phone number")
        # self.phone_number = phonenumbers.format_number(
        #     parsed_number, phonenumbers.PhoneNumberFormat.E164
        # )
        super().save(*args, **kwargs)

class ProductCategory(MPTTModel, TrackingChangeModel):
    name = models.CharField(verbose_name='Product category', max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    # parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,on_delete=models.CASCADE)
    store_operate = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank=True)

    class MPTTMeta:
        # level_attr = 'mptt_level'
        order_insertion_by = ['parent']

    class Meta:
        unique_together = (('parent', 'slug',))
        verbose_name_plural = 'Product Category'

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors = [i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[:i + 1]))
        return slugs
    def update(self, other):
        attr_names = ['id', 'name', 'slug', 'parent', 'store_operate']
        for an in attr_names:
            self.__setattr__(an, other.__getattribute__(an))

    def __unicode__(self):
        return '%s' % self.name
    def __str__(self):
        return self.name

class Product(SyncUpdateModel, TrackingChangeModel):
    title = models.CharField(max_length=512, null=False, blank=False)
    store_operate = models.ForeignKey(Store, on_delete=models.CASCADE, null=False, blank=False)
    price = models.FloatField(null=False, blank=False)
    discount = models.FloatField(null=True, blank=True)
    inventory = models.IntegerField(null=True, blank=True, default= 0)
    detail = models.CharField(max_length=1024, null=True, blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, null=False, blank=False)
    is_active= models.BooleanField(default=True)
    is_show_main_media = models.BooleanField(default=False)
    is_show_list_media = models.BooleanField(default=False)
    def thumbnail_directory_path(Client, filename):
        dirname = datetime.now().strftime('%y/%m/%d')
        return 'uploads/order-app/{0}/product/{1}'.format(dirname, filename)

    thumbnail = models.FileField(upload_to=thumbnail_directory_path, verbose_name="Hình ảnh",
                              default='', null=True)
    def __str__(self):
        return f'{self.title}'
    
    def save(self, force_insert=False, force_update=False):
        size = 300, 300
        super(Product, self).save(force_insert, force_update)
        if self.id is not None:

codes/RetailProject/templates/order-manager/pages/order/add-order.html
{% extends 'order-manager/layouts/base.html' %}
{% load static %}
{% block content %}

<!-- Section -->
{% if messages %}
  {% for message in messages %}
  <span id="message" data-message="{{message}}"></span>
  {% endfor %}
{% endif %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-2">
  <div class="d-block mb-4 mb-md-0">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
      <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
        <li class="breadcrumb-item">
          <a href="{% url 'dashboard' %}">
            <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
              </path>
            </svg>
          </a>
        </li>
        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Trang chủ</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{segment}}</li>
      </ol>
    </nav>
  </div>
</div>
<section class="mt-5 mt-lg-0 bg-soft flex-column align-items-start py-2">
  <h2 class="h4 mb-4 text-uppercase">Thêm mới đơn hàng</h2>
  <div class="row">
    <div class="col-12 col-xl-7 mb-4 mb-xl-0">
      <div class="card card-body border-0 shadow h-100">
        <h2 class="h5 mb-4">Thông tin đơn hàng</h2>
        <form method="" class="mt-4"id="order_form">
          {% csrf_token %}
          <div class="row">
            {{ form.store_operate }}
            {{ form.customer }}
            <div class="col-md-6 mb-3">
              <div>
                <label for="{{ form.order_type.id_for_label }}">{{form.order_type.label}}:</label>
                <div class="p-3 bg-gray-100 rounded">
                  {{ form.order_type }}
                </div>
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div>
                <label for="{{ form.discount.id_for_label }}">{{form.discount.label}}:</label>
                {{ form.discount }}
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div>
                <label for="{{ form.pay_type.id_for_label }}">{{form.pay_type.label}}:</label>
                <div class="p-3 bg-gray-100 rounded">
                  {{ form.pay_type }}
                </div>
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div>
                <label for="{{ form.status.id_for_label }}">{{form.status.label}}:</label>
                {{ form.status }}
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div class="d-flex flex-column">
                <label for="{{ form.is_paid.id_for_label }}">{{form.is_paid.label}}:</label>
                <div class="form-check form-switch">
                  {{ form.is_paid }}
                </div>
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <div class="d-flex flex-column">
                <div class="float-end mt-4">
                  <div class="d-flex justify-content-between mb-2">
                    <span class="text-gray">Tổng:</span><span class="fw-bold" id="total_price">0 đ</span>
                  </div>
                  <div class="d-flex justify-content-between mb-2">
                    <span class="text-gray">Giảm giá:</span><span class="fw-bold" id="discount_price">0 đ</span>
                  </div>
                  <div class="d-flex justify-content-between mb-2">
                    <span class="text-gray fs-4">Thanh toán:</span><span class="fw-bold fs-4 text-danger" id="total_payment">0 đ</span>
                  </div>
              </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="col-12 col-xl-5">
      <div class="card card-body border-0 shadow h-100">
        <div class="d-flex align-items-center justify-content-between border-2 border-bottom pb-4">
          <h2 class="h5">Danh sách món<span id="products_count"></span></h2>
          <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modal-select-product">+ Thêm món</button>
        </div>
        <div id="product_list" class="product-list py-3">
          Chưa có món được chọn
        </div>
      </div>
  </div>
  <div>
    <div class="d-flex justify-content-end gap-4 my-4">
      <a href="{% url 'orders' %}">
      <div class="btn btn-outline-tertiary">
          Trở lại
        </div>
      </a>
      <button type="button" class="btn btn-primary d-flex align-items-center" onclick="createOrder()">
        <svg style="height: 20px;" class="dropdown-icon text-white me-2" fill="white" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
          <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clip-rule="evenodd"></path>
        </svg>
        Tạo đơn hàng
      </button>
    </div>
  </div>
  <div class="modal fade" id="modal-select-product" tabindex="-1" role="dialog" aria-labelledby="modal-select-product" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h2 class="h4 modal-title">Thêm món</h2>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="mt-4">
                  <div class="row row-cols-1 row-cols-md-3 row-cols-xl-4 g-3 items">
                    {% for product in products %}
                      <div class="col">
                        <div href="{% url 'product_edit' %}?id={{product.id}}">
                          <div class="card shadow hover h-100">
                              <img class="card-img-top object-cover" height="150" alt="Product Image" src="/media/{{product.thumbnail}}" />
                            <div class="card-body p-2">
                              <h6 class="card-title text-truncate mb-0">{{product.title}}</h6>
                              <div class="d-flex justify-content-between">
                                <span class="text-info fst-italic fs-7">{{product.category}}</span>
                                <span class="text-danger fw-bold fs-7 float-end">{{product.price|floatformat:"2g"}}</span>
                              </div>
                              <div class="mt-2 d-flex justify-content-between">
                                <button onclick="addProduct('{{product.id}}')" class="btn btn-outline-primary w-100">Thêm</button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
          </div>
      </div>
  </div>
</section>

{% endblock content %}
{% block extra_js %}
  <script>
    let orderItems = new Map();
    const productsSerialize = JSON.parse('{{productsSerialize}}'.replace(/&quot;/g,'"'));
    const discountsSerialize = JSON.parse('{{discountsSerialize}}'.replace(/&quot;/g,'"'));

    function renderOrderItems () {
      updateBill();
      const stringHtml = Array.from(orderItems.values()).map(item =>
        `<div class="product-item bg-gray-100">
            <div class="thumbnail">
              <img src="/media/${item.product.fields.thumbnail}" alt="logo">
            </div>
            <div class="info">
              <div class="title">${item.product.fields.title}</div>
              <div class="note">Note: ${item.note}</div>
              <div class="quantity">Số lượng: <strong>${item.quantity}</strong></div>
              <div class="total">
                Giá: <strong>
                  ${(item.quantity*item.product.fields.price).toLocaleString('vi-VN', {
                    style: 'currency',
                    currency: 'VND',
                  })}
                </strong></div>
              <div class="d-flex justify-content-end gap-2 position-absolute bottom-0 end-0 p-2">
                <button class="btn btn-outline-primary">
                  <svg xmlns="http://www.w3.org/2000/svg" height="24px" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="dropdown-icon" >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                  </svg>

                </button>
                <button onclick="deleteProduct('${item.product.pk}')" type="button" class="btn btn-outline-danger d-flex align-items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" height="24px" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="dropdown-icon" >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                  </svg>

                </button>
              </div>
            </div>
          </div>`).join('')
      $('#product_list').html(orderItems.size ? stringHtml : 'Chưa có món được chọn');
      $('#products_count').html(`(${orderItems.size})`)
    }

    function addProduct(productId) {
      if (orderItems.has(+productId)) {
        const item = orderItems.get(+productId);
        item.quantity++;
      } else {
        const product = productsSerialize.find(pr => pr.pk === +productId);
        orderItems.set(+productId, { product: product, quantity: 1, note: '' });
      }
      renderOrderItems();
    }

    function deleteProduct(productId) {
      orderItems.delete(+productId)
      renderOrderItems()
    }
    function onDiscountChange() {
      updateBill()
    }
    function updateBill() {
      const formValues = $("form").serializeArray()
      const total = Array.from(orderItems.values()).map(item => item.quantity*item.product.fields.price).reduce((a,b) => a+b,0)
      let discountPrice = 0;
      const discountId = formValues.find(it => it.name === "discount").value
      if (discountId) {
        discountPrice = (discountsSerialize.find(dc => dc.pk === +discountId).fields.discount / 100 * total)
      }
      const payPrice = total - discountPrice;
      $('#total_price').html(total.toLocaleString('vi-VN', {
        style: 'currency',
        currency: 'VND',
      }))
      $('#discount_price').html('-'+ discountPrice.toLocaleString('vi-VN', {
        style: 'currency',
        currency: 'VND',
      }))
      $('#total_payment').html(payPrice.toLocaleString('vi-VN', {
        style: 'currency',
        currency: 'VND',
      }))
    }
        
    const createOrder = () => {
      // call api create order and payment
      $("#processing").show();
      let formData = new FormData(document.querySelector('#order_form'))
      formData.append('items', JSON.stringify(Array.from(orderItems.values()).map(item => ({...item ,id: item.product.pk}))))
      const crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');
      const dataPost = {
        async: true,
        crossDomain: true,
        processData: false,
        contentType: false,
        headers: { "X-CSRFToken": crf_token },
        mimeType: "multipart/form-data",
        url: `/order-api/create-order/`,
        method: "POST",
        data: formData,
      };
      $.ajax(dataPost).done(function (response) {
        
        notyf.open({
          type: 'success',
          message: "Tạo đơn hàng thành công",
          duration: 3000
        });
        setTimeout(() => {
          $("#processing").hide();
          window.location.assign(`/order-manager/order-detail?id=${JSON.parse(response)?.data?.id}`)
        }, 1000)
      }).fail(function (e) {
        $("#processing").hide();

          notyf.open({
            type: 'error',
            message: JSON.parse(e.responseText).message,
            duration: 3000
          });
      });
    }

    $(document).ready(function() {
      $("#id_thumbnail").val('');
      $('#id_thumbnail').change(function(e) {
        $('#thumbnail_image').attr('src', URL.createObjectURL(e.target.files[0]))
      })
      const messageText = $('#message').attr('data-message')
      if (messageText) {
        notyf.open({
          type: 'success',
          message: messageText,
          duration: 3000
        });
      }
      $('#message').remove();
    })

  </script>
{% endblock%}